In [1]:
import pandas as pd
url = "base_données.xlsx"
df = pd.read_excel(url)

In [2]:
df.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Precious Achiuwa,C,23,TOR,55,12,20.7,3.6,7.3,...,0.702,1.8,4.1,6.0,0.9,0.6,0.5,1.1,1.9,9.2
1,2,Steven Adams,C,29,MEM,42,42,27.0,3.7,6.3,...,0.364,5.1,6.5,11.5,2.3,0.9,1.1,1.9,2.3,8.6
2,3,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,14.9,...,0.806,2.5,6.7,9.2,3.2,1.2,0.8,2.5,2.8,20.4
3,4,Ochai Agbaji,SG,22,UTA,59,22,20.5,2.8,6.5,...,0.812,0.7,1.3,2.1,1.1,0.3,0.3,0.7,1.7,7.9
4,5,Santi Aldama,PF,22,MEM,77,20,21.8,3.2,6.8,...,0.750,1.1,3.7,4.8,1.3,0.6,0.6,0.8,1.9,9.0

In [3]:
#En NBA, les joueurs peuvent régulierement être Trade, c'est à dire échanger 
#chaque joueur apparait donc plusieurs fois si il a changé d'équipe pendant, trouvons le joueur avec le plus de points moyens
#Et on ne peut donc pas indexer par le nom du joueur 
df["total_point"] = df['G'] * df['PTS'] #on calcule tout d'abord le nombre total de point marqué
df.head()
#on remarque des nombre à virgules, surement un arrondi de la moyenne

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,total_point
0,1,Precious Achiuwa,C,23,TOR,55,12,20.7,3.6,7.3,...,1.8,4.1,6.0,0.9,0.6,0.5,1.1,1.9,9.2,506.0
1,2,Steven Adams,C,29,MEM,42,42,27.0,3.7,6.3,...,5.1,6.5,11.5,2.3,0.9,1.1,1.9,2.3,8.6,361.2
2,3,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,14.9,...,2.5,6.7,9.2,3.2,1.2,0.8,2.5,2.8,20.4,1530.0
3,4,Ochai Agbaji,SG,22,UTA,59,22,20.5,2.8,6.5,...,0.7,1.3,2.1,1.1,0.3,0.3,0.7,1.7,7.9,466.1
4,5,Santi Aldama,PF,22,MEM,77,20,21.8,3.2,6.8,...,1.1,3.7,4.8,1.3,0.6,0.6,0.8,1.9,9.0,693.0

In [4]:
#pour faire ca, on va grouper par nom de joueur, dans l'idée de voir qui à le plus marquer 
group = df.groupby("Player")
print(group.total_point.sum().idxmax()) #le joueur avec le nombre max de point marqué sur la saison
print(group.total_point.sum().max()) #le nombre max de point marqué sur la saison 
#mais cette donnée ne nous interessent finalement pas, il a joué beaucoup plus de match que les autres 
#on cherche donc le nombre de point par match en moyenne

Mikal Bridges
3336.2000000000003

ne sachant pas très bien manipuler les DF groupés et devant faire la division de deux somme 
(poin total / match total)
(j'ai l'impression que ce n'est pas comme un dataFrame, certaines fonction ne fonctionne pas)
on crée un nouveau dataframe

In [12]:
new_df = {}
Nom = []
Point_par_match = []
for name, joueur in group: #on parcours le dataframe associé à chaque joueur
    data = group.get_group(name)
    point = data.total_point.sum()
    match = data.G.sum()
    ppg = point/match
    Nom.append(name)
    Point_par_match.append(ppg)

new_df ={'Player' : Nom,
        'ppg' : Point_par_match}
df1 = pd.DataFrame(new_df)
df1.set_index('Player')
print(df1.idxmax)
print(df1.max())

<bound method DataFrame.idxmax of               Player        ppg
0         A.J. Green   4.400000
1        A.J. Lawson   3.736667
2         AJ Griffin   8.900000
3       Aaron Gordon  16.300000
4      Aaron Holiday   3.900000
..               ...        ...
534     Zach Collins  11.600000
535      Zach LaVine  24.800000
536       Zeke Nnaji   5.200000
537  Ziaire Williams   5.700000
538  Zion Williamson  26.000000

[539 rows x 2 columns]>
Player    Zion Williamson
ppg                  33.1
dtype: object

C'est donc le nouveau joueur Zion Williamson qui à le meilleur ratio point per game, cependant celui-ci a jouer très peu de match (blessure), il est donc plus compliqué de mesurer l'efficacité d'un joueur. La fatigue (surtout en NBA avec des matchs tout les 2-3 jours) est à prendre en compte. La variable à regarder ne semble ici pas évidente à premère vu.